import { createContext } from "react";
const data = [
  {
    id: 1,
    address: "Shtip, Vanco Prke 63/6",
    squareFeet: 13,
    term: "short term",
    type: "whole apartment",
    price: "15000",
    image: require("../images/apartment-images/1.jpeg"),
    brojNaSobi: 4,
  },
  {
    id: 2,
    address: "Skopje, Pitu Guli 16",
    squareFeet: 63,
    term: "short term",
    type: "shared",
    price: "2200",
    image: require("../images/apartment-images/2.jpeg"),
    brojNaSobi: 2,
  },
  {
    id: 3,
    address:
      "Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223",
    squareFeet: 63,
    term: "long term",
    type: "whole apartment",
    price: "15000",
    image: require("../images/apartment-images/3.jpeg"),
    brojNaSobi: 1,
  },
  {
    id: 4,
    address: "Shtip, Vanco Prke 63/6",
    squareFeet: 13,
    term: "short term",
    type: "shared",
    price: "15000",
    image: require("../images/apartment-images/1.jpeg"),
    brojNaSobi: 3,
  },
  {
    id: 5,
    address: "Skopje, Pitu Guli 16",
    squareFeet: 63,
    term: "long term",
    type: "whole apartment",
    price: "2200",
    image: require("../images/apartment-images/2.jpeg"),
    brojNaSobi: 5,
  },
  {
    id: 6,
    address:
      "Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223",
    squareFeet: 63,
    term: "short term",
    type: "shared",
    price: "15000",
    image: require("../images/apartment-images/3.jpeg"),
    brojNaSobi: 1,
  },
  {
    id: 7,
    address: "Shtip, Vanco Prke 63/6",
    squareFeet: 13,
    term: "long term",
    type: "whole apartment",
    price: "15000",
    image: require("../images/apartment-images/1.jpeg"),
    brojNaSobi: 2,
  },
  {
    id: 8,
    address: "Skopje, Pitu Guli 16",
    squareFeet: 63,
    term: "short term",
    type: "shared",
    price: "2200",
    image: require("../images/apartment-images/2.jpeg"),
    brojNaSobi: 1,
  },
  {
    id: 9,
    address:
      "Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223",
    squareFeet: 63,
    term: "long term",
    type: "whole apartment",
    price: "15000",
    image: require("../images/apartment-images/3.jpeg"),
    brojNaSobi: 3,
  },
  {
    id: 10,
    address: "Shtip, Vanco Prke 63/6",
    squareFeet: 13,
    term: "short term",
    type: "shared",
    price: "15000",
    image: require("../images/apartment-images/1.jpeg"),
    brojNaSobi: 3,
  },
  {
    id: 11,
    address: "Skopje, Pitu Guli 16",
    squareFeet: 63,
    term: "long term",
    type: "whole apartment",
    price: "2200",
    image: require("../images/apartment-images/2.jpeg"),
    brojNaSobi: 4,
  },
  {
    id: 12,
    address:
      "Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223, Ohrid, Pozadi Karpos 223",
    squareFeet: 63,
    term: "short term",
    type: "shared",
    price: "15000",
    image: require("../images/apartment-images/3.jpeg"),
    brojNaSobi: 2,
  },
];
export const ApartmentData = createContext(data);
